### ISSUE TITLE
[1.4.0 regression] `import { Bonjour } from 'bonjour-service'` no longer exists

### ISSUE THREAD

**Issue by andersk** [onlxltd/bonjour-service#79]
```console
$ npm i bonjour-service@1.3.0
$ node -e "import { Bonjour } from 'bonjour-service'; console.log(Bonjour)"
[class Bonjour]
$ npm i bonjour-service@1.4.0
$ node -e "import { Bonjour } from 'bonjour-service'; console.log(Bonjour)"
file:///tmp/test/[eval1]:1
import { Bonjour } from 'bonjour-service'; console.log(Bonjour)
         ^^^^^^^
SyntaxError: Named export 'Bonjour' not found. The requested module 'bonjour-service' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'bonjour-service';
const { Bonjour } = pkg;

    at #asyncInstantiate (node:internal/modules/esm/module_job:326:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:429:5)
    at async node:internal/modules/esm/loader:246:26
    at async ModuleLoader.executeModuleJob (node:internal/modules/esm/loader:243:20)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)

Node.js v24.15.0
```

This was broken by commit 3be3b182bf44a1c495494b92e1a275a097922214. `cjs-module-lexer` does not consider `class` properties to be named exports (and this [won’t change](https://github.com/nodejs/cjs-module-lexer#project-status)).

**Comment by mdidon** [comment]
@andersk Thanks for highlighting.
PR #80 contains changes to address, let me know that's it working for you and I'll get a version pushed.

**Comment by mdidon** [comment]
Resolved in v1.4.1

**Comment by Nerivec** [comment]
We moved to `import Bonjour` after 1.4.0 broke `import {Bonjour}` (in package with `"type": "module"`).
1.4.1 now appears to break that one?
```
error TS2351: This expression is not constructable.
  Type 'typeof import("/node_modules/bonjour-service/dist/index")' has no construct signatures.
```
from doing
```ts
import Bonjour from "bonjour-service";
const bonjour = new Bonjour();
```

**Comment by mdidon** [comment]
@Nerivec Would you be able to share your package.json
1.4.1 should have already resolved this and I added a test stage that does appear to confirm that is works.

**Comment by Nerivec** [comment]
Did not investigate further (yet), it was just a dependabot CI that brought this out, thought it was worth a quick feedback:
https://github.com/Nerivec/ember-zli/actions/runs/27521174050/job/81339250517
Note: the package.json of the repo has stuff related to oclif, but CI broke on a simple `tsc -b`, so, not related to any of that.

**Comment by mdidon** [comment]
@Nerivec Closing this as I can see that your repo above was using 1.4.0 which was identified previously to have import issues.
This was resolved in 1.4.1.

**Comment by Nerivec** [comment]
@mdidon This is incorrect. The workflow run I linked was a dependabot update to 1.4.1...
https://github.com/Nerivec/ember-zli/pull/181

**Comment by mdidon** [comment]
Understood, I was referencing the incorrect package-lock.json file in your repo.

We've retested the imports both for ESM and commonjs and both do seem to be working in 1.4.1 and 1.4.2 for default and named.
cjs-module-lexer also identifies `[ '__esModule', 'Browser', 'Service', 'Bonjour', 'default' ]` as available exports.

**Comment by Nerivec** [comment]
Still breaks in practice though, here's a freshly run dependabot:
https://github.com/Nerivec/ember-zli/pull/185
As you can see, same error as before
```
Error: src/utils/port.ts(12,25): error TS2351: This expression is not constructable.
  Type 'typeof import("/home/runner/work/ember-zli/ember-zli/node_modules/bonjour-service/dist/index")' has no construct signatures.
Error: src/utils/port.ts(14,41): error TS7006: Parameter 'service' implicitly has an 'any' type.
```

Also publint is alerting on the export pattern used: https://publint.dev/bonjour-service@1.4.2
(though it mentions bundlers, but here it's happening with nodenext & plain tsc)

**Comment by andersk** [comment]
You can reproduce that failure like this:

```console
$ npm i @types/node bonjour-service typescript
$ >test.mts echo 'import Bonjour from "bonjour-service"; new Bonjour'
$ npx tsc --module nodenext --types node test.mts
test.mts:1:44 - error TS2351: This expression is not constructable.
  Type 'typeof import("/tmp/test/node_modules/bonjour-service/dist/index")' has no construct signatures.

1 import Bonjour from "bonjour-service"; new Bonjour
                                             ~~~~~~~


Found 1 error in test.mts:1
```

**Comment by Nerivec** [comment]
To complement above:
```ts
import Bonjour from "bonjour-service";
console.log(Bonjour);
console.log(Bonjour.Bonjour);
console.log(Bonjour.default);
```
```
<ref *1> [class Bonjour extends Bonjour] {
  Bonjour: [Circular *1],
  Service: [class Service extends EventEmitter],
  Browser: [class Browser extends EventEmitter],
  default: [Circular *1]
}
<ref *1> [class Bonjour extends Bonjour] {
  Bonjour: [Circular *1],
  Service: [class Service extends EventEmitter],
  Browser: [class Browser extends EventEmitter],
  default: [Circular *1]
}
<ref *1> [class Bonjour extends Bonjour] {
  Bonjour: [Circular *1],
  Service: [class Service extends EventEmitter],
  Browser: [class Browser extends EventEmitter],
  default: [Circular *1]
}
```

These work **but typing fails.**
```ts
import Bonjour from "bonjour-service";
const b = new Bonjour.Bonjour();
```
```ts
import Bonjour from "bonjour-service";
const b = new Bonjour.default();
```

---

For good measure, this works, and typing is fine...
```ts
import {Bonjour} from "bonjour-service";
console.log(Bonjour);
const b = new Bonjour();
```
```
<ref *1> [class Bonjour extends Bonjour] {
  Bonjour: [Circular *1],
  Service: [class Service extends EventEmitter],
  Browser: [class Browser extends EventEmitter],
  default: [Circular *1]
}
```

**Comment by mdidon** [comment]
@andersk @Nerivec I've made some changes to src/index.ts which should hopefully resolve the issue.
Let me know if this is working for you and I'll get this pushed.

**Comment by mdidon** [comment]
This issue should now be resolved in v1.4.3. I'll go ahead and close this issue.
Anything further, just add below.
Thanks

**Comment by andersk** [comment]
1.4.3 re-broke usage of `Bonjour`, `Service`, and `Browser` as a type.

```ts
test.mts:1:51 - error TS2749: 'Bonjour' refers to a value, but is being used as a type here. Did you mean 'typeof Bonjour'?

1 import {Bonjour} from "bonjour-service"; const b: Bonjour = new Bonjour
                                                    ~~~~~~~


Found 1 error in test.mts:1
```

(Worked in 1.3.0, 1.4.1, 1.4.2; fails in 1.4.0, 1.4.3.)

- #84

**Comment by mdidon** [comment]
@andersk Thanks for catching that.
I've pushed 1.4.4 to resolve this now.
